/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_na_ho_pricer_jni_QuantJNI */

#ifndef _Included_com_na_ho_pricer_jni_QuantJNI
#define _Included_com_na_ho_pricer_jni_QuantJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_na_ho_pricer_jni_QuantJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_na_1ho_pricer_jni_QuantJNI_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_na_ho_pricer_jni_QuantJNI
 * Method:    priceFixedRateBond
 * Signature: (IIIIIDDDDI[I[I[I[I[I[I[D[DIIIIIID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_na_1ho_pricer_jni_QuantJNI_priceFixedRateBond
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jdouble, jdouble, jdouble, jdouble, jint, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jdoubleArray, jdoubleArray, jint, jint, jint, jint, jint, jint, jdouble);

/*
 * Class:     com_na_ho_pricer_jni_QuantJNI
 * Method:    priceEuropeanOptionMCSobol
 * Signature: (IIIIIIIIIIDDDDDII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_na_1ho_pricer_jni_QuantJNI_priceEuropeanOptionMCSobol
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
