server:
  port : 8083

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      #value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: dataprovider
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

    bootstrap-servers: localhost:9092

  datasource:
      url: jdbc:postgresql://192.168.70.130:5432/equity
      username: equity
      password: 1234


  jpa:
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #hibernate.naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
    #hibernate.naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
  #database-platform: org.hibernate.dialect.PostgreSQLDialect

spring.redis:
  host: 192.168.70.130
  port: 6379
  password: null
  database: 0

